### PR TITLE
Add translation to Persian language

### PR DESCRIPTION
**Pull request by abmalakh**

### CODE REVIEW

**Comment by andrejbauer** [comment]
We already have Farsi by @fatimahahmadi. Could you coordinate with him what to do? I understand that Farsi and Persian is the same language, right?

**Comment by andrejbauer** [comment]
I used this one because the other Farsi pull request did not work. Thanks!

**Comment by abmalakh** [comment]
> Thanks

Thank you very much.

**Comment by abmalakh** [comment]
> Could you coordinate with him what to do?

They are the same. You can choose each of them. Thanks.

**Pull request merged**
