### PR TITLE
Added collisions with walls and maybe slightly improved the text

### PR DESCRIPTION
**Pull request by ghost**
Didn't do a lot of JS yet but it seems to work locally.

### CODE REVIEW

**Comment by andrejbauer** [comment]
Do you think there's any benefit in having the balls bounce off walls? I am inclined to accept only the changes to English. In general I intend to resist adding bells and whistles to the simulator.

**Comment by ghost** [comment]
Well it removes teleportation. It is just a suggestion and an excuse to learn some JS so no problem if you discard that commit.

**Comment by andrejbauer** [comment]
It's not teleportation. The balls are moving on a torus (laid out as a rectangle), all movement is continuous. Why live in a box when you can live on a torus?

**Comment by ghost** [comment]
Oh sorry I assumed the earth was spherical, aka a manifold and that we were simulating a small closed part of it.

**Comment by andrejbauer** [comment]
I apologize for closing this one without accepting. I don't really see the point of having walls (but if others think they should be there, speak up), and in the meantime I got a professional to look at the English text. Many thanks though!

**Pull request closed without merging**
