### PR TITLE
copy-edits in German version

### PR DESCRIPTION
**Pull request by backens**
Fixed a few typos and made some sentences flow better (I'm a native German speaker).

### CODE REVIEW

**Comment by andrejbauer** [comment]
Many thanks. There is a conflict with some changes I made in parallel with you. I tried to change "Social distancing" to a German phrase. Could you help with that as well? If you look at "Resolve conflicts" you will see I used "Meidung sozialer Kontakte" which was suggested to me on Twitter.

The translation is a bit tricky because we need the title to be a single line that is not too long, and "social distancing" should be a phrase which siginfies a quantity (such as distance). I naively used "Meidungdistanz" but that's likely going to make German speakers cringe or something.

Do you have a suggestion?

**Comment by backens** [comment]
"Meidung sozialer Kontakte" does indeed seem to be the term used by the media. For the quantity, I've decided to go for "Meidunggstärke" (“strength of avoidance") -- it's not great but sounds a little better to me than "Meidungsdistanz". I've also made a couple of other small changes e.g. changing the word order in the title to make it sound more natural.

**Comment by andrejbauer** [comment]
Excellent, thanks!

**Comment by Nikolaj-K** [comment]
Note that "Meidung sozialer Kontakte" isn't just a noun or verb as such, though. But I'd also not advice to "Sozialkontaktmeidung". Funny interlude:
[Rinderkennzeichnungs- und Rindfleischetikettierungsüberwachungsaufgabenübertragungsgesetz](https://en.wikipedia.org/wiki/Rinderkennzeichnungs-_und_Rindfleischetikettierungs%C3%BCberwachungsaufgaben%C3%BCbertragungsgesetz).
Or
[Führerdiskriminantenproduktformel](https://en.wikipedia.org/wiki/Conductor-discriminant_formula).
I don't quite see who you think would benefit from that translation of it, I'm sure even people who never seen English would read "social distance" as "soziale Distanz." At least then it's clear that it's related to the notion in the Corona situation, and not about the correlation of social isolation and consumption of anti-depressants or something else you could simulate that relates to not wanting to be around others. 
It's a bit like if you hired an external editor for your linear algebra book draft and he'd want to translate eigenvalue to selfvalue because, after all, Eigen isn't an English word 😄

I wrote "abgelaufenden" in "abgelaufenden Sekunden" (seconds that have passed) on purpose, since here it's literally that you want to display the seconds passed since you press the start button (for contrast, I could also simulate the growth of the population density of classic Rome and the GUI would show me the years passing by then the unit would be removed from actual perceived simulation runtime).
But overall good edits 👍

**Comment by Nikolaj-K** [comment]
>Edit the contents of the file italan.html.

typo

**Comment by andrejbauer** [comment]
@Nikolaj-K so what specific corrections do you propose, if any? I am mostly unhappy about the extremely long title, and my instinct is not to mix English with German (too much). Surely, Angela Merke doesn't say "social distance" on TV?

**Comment by backens** [comment]
From what I can tell, there isn't really a single term like "social distancing" that's actively used in the German media. I got "Meidung sozialer Kontakte" from some articles on tagesschau.de, though I don't now remember which ones. In yesterday's speech, Angela Merkel was just talking about "Distanz", but on it's own that's not very specific. I'd be happy for suggestions!

**Comment by andrejbauer** [comment]
I may be a Bauer but I've only had two years of German in school, and having a girlfriend from Switzerland didn't really help that much, so I'll let the native speakers decide.

**Pull request merged**
